--NDefines 

--NGame

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 90
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 50

--NDiplo

NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 30
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 9
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 10.0
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.1
NDefines.NDiplomacy.WAR_SCORE_AUTONOMY_FACTOR = 0.9
NDefines.NPolitics.ARMY_LEADER_COST = 10

--NCountry  
NDefines.NCountry.VP_TO_SUPPLY_BASE = 1.3
NDefines.NCountry.SUPPLY_BASE_MULT = 1.15
NDefines.NCountry.SUPPLY_PATH_MAX_DISTANCE = 18
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.35
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.15
NDefines.NCountry.EVENT_PROCESS_OFFSET = 30
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.03
NDefines.NCountry.STATE_OCCUPATION_COST_MULTIPLIER = 0.015
NDefines.NCountry.MAX_CONVOYS_BEING_RAIDED_WAR_SUPPORT_IMPACT = -0.3
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 150.0
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.1
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 28
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1
NDefines.NCountry.BASE_FUEL_GAIN = 1.5
NDefines.NCountry.BASE_FUEL_CAPACITY = 100000


--NProduction
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 10
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 40
NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.15


--NTechnology

NDefines.NTechnology.MAX_TECH_SHARING_BONUS = 0.8
NDefines.NTechnology.LICENSE_PRODUCTION_TECH_BONUS = 0.6

--NBuildings
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NBuildings.INFRA_TO_SUPPLY = 2.25



--NMilitary 
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 30
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 60
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 7
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 750
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 750
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 750
NDefines.NMilitary.LAND_AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.03
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.25
NDefines.NMilitary.ANTI_AIR_TARGETTING_TO_CHANCE = 0.06
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2
NDefines.NMilitary.EXPEDITIONARY_FIELD_EXPERIENCE_SCALE = 0.25
NDefines.NMilitary.UNIT_EXP_LEVELS = { 0.1, 0.3, 0.7, 0.9 }
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.001
NDefines.NMilitary.LEND_LEASE_FIELD_EXPERIENCE_SCALE = 0.0025
NDefines.NMilitary.SUPPLY_USE_FACTOR_INACTIVE = 0.50
NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.9
NDefines.NMilitary.NON_CORE_SUPPLY_SPEED = -0.4
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01
NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 20
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 10
NDefines.NMilitary.NAVAL_EQUIPMENT_BASE_COST = 20
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 25
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 10
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.1
NDefines.NMilitary.MAX_NUM_TRAITS = 11
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.06
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.2
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 0.0
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 0.0

NDefines.NMilitary.ARMY_STRATEGIC_DEPLOYMENT_FUEL_MULT = 0.5
NDefines.NMilitary.ARMY_IDLE_FUEL_MULT = 0.1
NDefines.NMilitary.OUT_OF_FUEL_SPEED_MULT = 0.5
NDefines.NMilitary.FUEL_CAPACITY_DEFAULT_HOURS = 192



--NAir 
NDefines.NAir.AIR_WING_MAX_SIZE = 1600
NDefines.NAir.DETECT_CHANCE_FROM_OCCUPATION = 0.08
NDefines.NAir.DETECT_CHANCE_FROM_AIRCRAFTS_EFFECTIVE_COUNT = 4000
NDefines.NAir.DETECT_CHANCE_FROM_AIRCRAFTS = 0.7
NDefines.NAir.FIELD_EXPERIENCE_SCALE = 0.002
NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.07
NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_SHIP_CHANCE = 0.02
NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.8
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 2
NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0

NDefines.NAir.MISSION_COMMAND_POWER_COSTS = {  -- command power cost per plane to create a mission
		0.0, -- AIR_SUPERIORITY
		0.0, -- CAS		
		0.0, -- INTERCEPTION	
		0.0, -- STRATEGIC_BOMBER
		0.0, -- NAVAL_BOMBER	
		0.0, -- DROP_NUKE		
		0.0, -- PARADROP		
		0.0, -- NAVAL_KAMIKAZE	
        0.0, -- PORT_STRIKE		
		0.0, -- AIR_SUPPLY		
		0.0, -- TRAINING
		0.0, -- NAVAL_MINES_PLANTING
		0.0, -- NAVAL_MINES_SWEEPING
	}

--NNavy 
NDefines.NNavy.COMBAT_LOW_ORG_HIT_CHANCE_PENALTY = -0.4
NDefines.NNavy.COMBAT_BASE_CRITICAL_CHANCE = 0.05
NDefines.NNavy.COMBAT_ARMOR_PIERCING_DAMAGE_REDUCTION = -0.6

NDefines.NNavy.EXPERIENCE_FACTOR_CARRIER_GAIN = 0.05
NDefines.NNavy.AMPHIBIOUS_LANDING_PENALTY = -0.6
NDefines.NNavy.CONVOY_ATTACK_BASE_FACTOR = 0.1
NDefines.NNavy.NAVAL_INVASION_PREPARE_HOURS = 144
NDefines.NNavy.NAVAL_COMBAT_RESULT_TIMEOUT_YEARS = 1
NDefines.NNavy.CONVOY_LOSS_HISTORY_TIMEOUT_MONTHS = 12
NDefines.NNavy.NAVY_VISIBILITY_BONUS_ON_RETURN_FOR_REPAIR = 0.6
NDefines.NNavy.NAVAL_TRANSFER_BASE_SPEED = 7
NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.6
NDefines.NNavy.CARRIER_STACK_PENALTY = 8
NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 0.9
NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.30
NDefines.NNavy.MANPOWER_LOSS_RATIO_ON_SUNK = 0.9
NDefines.NNavy.PRIDE_OF_THE_FLEET_UNASSIGN_COST = 50
NDefines.NNavy.NAVY_REPAIR_BASE_SEARCH_BOOST_FOR_SAME_COUNTRY = 9
NDefines.NNavy.OUT_OF_FUEL_ATTACK_FACTOR = -0.1
NDefines.NNavy.OUT_OF_FUEL_EVASION_FACTOR = -0.75
NDefines.NNavy.ATTRITION_DAMAGE_STR = 0.02
NDefines.NNavy.NAVAL_MINES_ACCIDENT_CRITICAL_HIT_CHANCES = 0.21
NDefines.NNavy.NAVAL_MINES_ACCIDENT_ORG_LOSS_FACTOR = 0.7
NDefines.NNavy.TRAINING_MAX_DAILY_COUNTRY_EXP = 2.0
NDefines.NNavy.BASE_SPOTTING_FROM_AIR_SUPERIORITY = 10
NDefines.NNavy.BASE_SPOTTING_DECRYPTION_MULT = 2.0
NDefines.NNavy.UNIT_TRANSFER_SPOTTING_SPEED_MULT = 4.0

NDefines.NNavy.NAVAL_MINES_PLANTING_SPEED_MULT = 0.007
NDefines.NNavy.NAVAL_MINES_SWEEPING_SPEED_MULT = 0.006

NDefines.NNavy.MIN_GUN_COOLDOWN = 0.2
NDefines.NNavy.BASE_GUN_COOLDOWNS = { 
        2.0,    -- big guns
        8.0,    -- torpedos
        2.0,    -- small guns
}

--NAI 
NDefines.NAI.GARRISON_FRACTION = 1
NDefines.NAI.BASE_RELUCTANCE = 10
NDefines.NAI.DIPLOMATIC_ACTION_RANDOM_FACTOR = 0
NDefines.NAI.DIPLOMACY_CREATE_FACTION_FACTOR = 0
NDefines.NAI.DIPLOMACY_REJECTED_WAIT_MONTHS_BASE = 6
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 14
NDefines.NAI.RESEARCH_BONUS_FACTOR = 1
NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1
NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 1
NDefines.NAI.WANTED_UNITS_INDUSTRY_FACTORY = 0
NDefines.NAI.DYNAMIC_STRATEGIES_THREAT_FACTOR = 0
NDefines.NAI.LOCATION_BALANCE_TO_ADVANCE = 1
NDefines.NAI.DIVISION_UPGRADE_MIN_XP = 1000
NDefines.NAI.DIVISION_CREATE_MIN_XP = 1000
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 1000
NDefines.NAI.UPGRADE_XP_RUSH_UPDATE = 1000
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -1
NDefines.NAI.CALL_ALLY_BASE_DESIRE = -75
NDefines.NAI.CALL_ALLY_DEMOCRATIC_DESIRE = -75
NDefines.NAI.CALL_ALLY_NEUTRAL_DESIRE = -75
NDefines.NAI.CALL_ALLY_COMMUNIST_DESIRE = -75
NDefines.NAI.LENDLEASE_FRACTION_OF_PRODUCTION = 0.8
NDefines.NAI.NEIGHBOUR_WAR_THREAT_FACTOR = 0
NDefines.NAI.POTENTIAL_ALLY_JOIN_WAR_FACTOR = 0
NDefines.NAI.POTENTIAL_FUTURE_ENEMY_FACTOR = 0
NDefines.NAI.NEUTRAL_THREAT_PARANOIA = 0
NDefines.NAI.DIFFERENT_FACTION_THREAT = 0
NDefines.NAI.PLAN_MOVE_MIN_ORG_TO_ENEMY_PROVINCE = 100
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.9
NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 0.2
NDefines.NAI.SEND_VOLUNTEER_EVAL_MAJOER_POWER = 0
NDefines.NAI.RELATIVE_STRENGTH_TO_INVADE = 1
NDefines.NAI.GIVE_STATE_CONTROL_BASE_SCORE = 20
NDefines.NAI.IRRATIONALITY_LAMBDA = 0
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0
NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 0
NDefines.NAI.EASY_TARGET_FRONT_IMPORTANCE = 0
NDefines.NAI.MICRO_POCKET_SIZE = 0
NDefines.NAI.POCKET_DISTANCE_MAX = 0
NDefines.NAI.BASE_DISTANCE_TO_CARE = 300.0
NDefines.NAI.ORG_UNIT_STRONG = 1
NDefines.NAI.STR_UNIT_STRONG = 1
NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.9
NDefines.NAI.STATE_GARRISON_MAX_UNITS = 0
NDefines.NAI.MAX_ALLOWED_NAVAL_DANGER = 40
NDefines.NAI.TRANSFER_DANGER_HOSTILE_SHIPS = 40
NDefines.NAI.DIPLOMACY_FACTION_WAR_WANTS_HELP = 0
NDefines.NAI.CALL_ALLY_WT_LIMIT = 10000
NDefines.NAI.CALL_ALLY_FASCIST_DESIRE_WT = -10000


--NFocus 		
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

--Graph
NDefines_Graphics.NFrontend.CAMERA_MIN_HEIGHT = 30.0
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {250, 350, 600}
NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 900
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 300.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_A = 300
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 300
NDefines_Graphics.NGraphics.ROOT_FRONT_OFFSET = 2